import 'package:flutter/material.dart';

/// Maps string icon keys (stored in DB) to Flutter [IconData].
/// Comprehensive registry with 120+ categorized icons.
abstract final class AppIcons {
  static const Map<String, IconData> _registry = {
    // ── Food & Dining ──────────────────────────────────────
    'utensils': Icons.restaurant,
    'chef_hat': Icons.soup_kitchen,
    'shopping_basket': Icons.shopping_basket,
    'coffee': Icons.coffee,
    'cookie': Icons.cookie,
    'pizza': Icons.local_pizza,
    'burger': Icons.lunch_dining,
    'ice_cream': Icons.icecream,
    'drink': Icons.local_bar,
    'wine': Icons.wine_bar,
    'cake': Icons.cake,
    'bakery': Icons.bakery_dining,
    'apple': Icons.apple,
    'fastfood': Icons.fastfood,
    'dining': Icons.dinner_dining,
    'egg': Icons.egg,
    'ramen': Icons.ramen_dining,
    'rice': Icons.rice_bowl,
    'kebab': Icons.kebab_dining,
    'breakfast': Icons.free_breakfast,
    'liquor': Icons.liquor,

    // ── Transport & Travel ─────────────────────────────────
    'car': Icons.directions_car,
    'fuel': Icons.local_gas_station,
    'taxi': Icons.local_taxi,
    'bus': Icons.directions_bus,
    'motorcycle': Icons.two_wheeler,
    'bicycle': Icons.pedal_bike,
    'electric_scooter': Icons.electric_scooter,
    'electric_car': Icons.electric_car,
    'electric_bike': Icons.electric_bike,
    'train': Icons.train,
    'subway': Icons.subway,
    'boat': Icons.directions_boat,
    'plane': Icons.flight,
    'luggage': Icons.luggage,
    'hotel': Icons.hotel,
    'parking': Icons.local_parking,
    'map': Icons.map,
    'rocket': Icons.rocket_launch,
    'sailing': Icons.sailing,
    'toll': Icons.toll,

    // ── Shopping & Fashion ─────────────────────────────────
    'shopping_bag': Icons.shopping_bag,
    'shopping_cart': Icons.shopping_cart,
    'store': Icons.storefront,
    'shirt': Icons.checkroom,
    'watch': Icons.watch,
    'diamond': Icons.diamond,
    'gift': Icons.card_giftcard,
    'package': Icons.inventory_2,
    'scissors': Icons.content_cut,
    'brush': Icons.brush,
    'palette': Icons.palette,
    'local_offer': Icons.local_offer,
    'sell': Icons.sell,
    'loyalty': Icons.loyalty,
    'dry_cleaning': Icons.dry_cleaning,
    'face': Icons.face,
    'auto_awesome': Icons.auto_awesome,

    // ── Bills, Housing & Services ──────────────────────────
    'receipt': Icons.receipt_long,
    'home': Icons.home,
    'apartment': Icons.apartment,
    'wifi': Icons.wifi,
    'zap': Icons.bolt,
    'water': Icons.water_drop,
    'repeat': Icons.repeat,
    'clean': Icons.cleaning_services,
    'laundry': Icons.local_laundry_service,
    'build': Icons.build,
    'handyman': Icons.handyman,
    'yard': Icons.yard,
    'kitchen': Icons.kitchen,
    'bed': Icons.bed,
    'chair': Icons.chair,
    'ac_unit': Icons.ac_unit,
    'solar_power': Icons.solar_power,
    'iron': Icons.iron,
    'security': Icons.security,

    // ── Health & Fitness ───────────────────────────────────
    'heart': Icons.favorite,
    'pill': Icons.medication,
    'stethoscope': Icons.medical_services,
    'hospital': Icons.local_hospital,
    'dumbbell': Icons.fitness_center,
    'run': Icons.directions_run,
    'pool': Icons.pool,
    'spa': Icons.spa,
    'self_improvement': Icons.self_improvement,
    'sports_tennis': Icons.sports_tennis,
    'sports_golf': Icons.sports_golf,
    'sports_volleyball': Icons.sports_volleyball,
    'sports_mma': Icons.sports_mma,
    'hiking': Icons.hiking,
    'healing': Icons.healing,
    'vaccines': Icons.vaccines,

    // ── Tech & Entertainment ───────────────────────────────
    'laptop': Icons.laptop,
    'smartphone': Icons.smartphone,
    'tv': Icons.tv,
    'headphones': Icons.headphones,
    'music': Icons.music_note,
    'mic': Icons.mic,
    'piano': Icons.piano,
    'camera': Icons.camera_alt,
    'videocam': Icons.videocam,
    'film': Icons.movie,
    'clapperboard': Icons.theaters,
    'theater': Icons.theater_comedy,
    'gamepad': Icons.sports_esports,
    'sports_soccer': Icons.sports_soccer,
    'sports_cricket': Icons.sports_cricket,
    'sports_basketball': Icons.sports_basketball,
    'celebration': Icons.celebration,
    'casino': Icons.casino,
    'subscriptions': Icons.subscriptions,
    'code': Icons.code,
    'cloud': Icons.cloud,

    // ── Education, Family & Nature ─────────────────────────
    'school': Icons.school,
    'book': Icons.menu_book,
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'toys': Icons.toys,
    'family': Icons.family_restroom,
    'pets': Icons.pets,
    'cruelty_free': Icons.cruelty_free,
    'forest': Icons.forest,
    'park': Icons.park,
    'science': Icons.science,
    'psychology': Icons.psychology,

    // ── Finance, Work & Income ─────────────────────────────
    'banknote': Icons.payments,
    'briefcase': Icons.work,
    'landmark': Icons.account_balance,
    'credit_card': Icons.credit_card,
    'chart_line': Icons.show_chart,
    'trending_up': Icons.trending_up,
    'savings': Icons.savings,
    'crypto': Icons.currency_bitcoin,
    'wallet': Icons.account_balance_wallet,
    'calculate': Icons.calculate,
    'gold': Icons.monetization_on,
    'paid': Icons.paid,
    'request_quote': Icons.request_quote,
    'gavel': Icons.gavel,
    'handshake': Icons.handshake,
    'volunteer_activism': Icons.volunteer_activism,
    'lock': Icons.lock,
    'sync': Icons.sync,
    'bribe': Icons.privacy_tip,
    'shh': Icons.visibility_off,

    // ── Miscellaneous ──────────────────────────────────────
    'moon': Icons.dark_mode,
    'sun': Icons.light_mode,
    'bell': Icons.notifications,
    'user': Icons.person,
    'shield': Icons.shield,
    'settings': Icons.settings,
    'star': Icons.star,
    'more_horizontal': Icons.more_horiz,
  };

  static IconData get(String key) => _registry[key] ?? Icons.circle;
}
